Repository DataDog/helm-charts, pull requests merged in 2023-01, with the labels that each got.

#836 Updating Datadog Operator dependency on Datadog Monitor/Agent CRD
  charts/datadog-operator/CHANGELOG.md
  charts/datadog-operator/Chart.lock
  charts/datadog-operator/Chart.yaml
  charts/datadog-operator/README.md
  charts/datadog-operator/values.yaml
Labels: not-merge

#884 introduce container-helm-chart-maintainers in codeowners
  .github/CODEOWNERS
Labels: tooling

#883 feat(datadog): Secret annotations support
  charts/datadog/CHANGELOG.md
  charts/datadog/Chart.yaml
  charts/datadog/README.md
  charts/datadog/ci/secret-with-dynamic-annotations-values.yaml
  charts/datadog/templates/secret-api-key.yaml
  charts/datadog/templates/secret-application-key.yaml
  charts/datadog/templates/secret-cluster-agent-token.yaml
  charts/datadog/values.yaml
Labels: enhancement, chart/datadog

#811 [observability-pipelines-worker] Initial commit
  .github/CODEOWNERS
  charts/observability-pipelines-worker/.helmignore
  charts/observability-pipelines-worker/CHANGELOG.md
  charts/observability-pipelines-worker/Chart.yaml
  charts/observability-pipelines-worker/README.md
  charts/observability-pipelines-worker/README.md.gotmpl
  charts/observability-pipelines-worker/ci/all-values.yaml
  charts/observability-pipelines-worker/ci/dupe-ports-values.yaml
  charts/observability-pipelines-worker/ci/extra-volume-values.yaml
  charts/observability-pipelines-worker/ci/extraContainers-and-extraVolumeMounts-values.yaml
  charts/observability-pipelines-worker/ci/extraContainers-values.yaml
  charts/observability-pipelines-worker/ci/ingress-values.yaml
  charts/observability-pipelines-worker/ci/initContainers-values.yaml
  charts/observability-pipelines-worker/ci/kubeval-values.yaml
  charts/observability-pipelines-worker/ci/manual-port-values.yaml
  charts/observability-pipelines-worker/ci/serviceHeadless-disabled.yaml
  charts/observability-pipelines-worker/ci/templated-config-values.yaml
  charts/observability-pipelines-worker/templates/NOTES.txt
  charts/observability-pipelines-worker/templates/_helpers.tpl
  charts/observability-pipelines-worker/templates/_pod.tpl
  charts/observability-pipelines-worker/templates/configmap.yaml
  charts/observability-pipelines-worker/templates/hpa.yaml
  charts/observability-pipelines-worker/templates/ingress.yaml
  charts/observability-pipelines-worker/templates/pdb.yaml
  charts/observability-pipelines-worker/templates/secret-api-key.yaml
  charts/observability-pipelines-worker/templates/secret-configuration-key.yaml
  charts/observability-pipelines-worker/templates/service-headless.yaml
  charts/observability-pipelines-worker/templates/service.yaml
  charts/observability-pipelines-worker/templates/serviceaccount.yaml
  charts/observability-pipelines-worker/templates/statefulset.yaml
  charts/observability-pipelines-worker/values.yaml
Labels: editorial review

#893 [datadog] Fix missing agent PSP capability (#881)
  charts/datadog/CHANGELOG.md
  charts/datadog/Chart.yaml
  charts/datadog/README.md
  charts/datadog/values.yaml
Labels: bug, chart/datadog
